---
output:
  pdf_document:
    latex_engine: lualatex
    template: braga_php-cv-template.tex
date: Oct 13, 2021
first: Pedro Henrique P. 
last: Braga
email: ph.pereirabraga@gmail.com
emaildesc: "ph.pereirabraga [at] gmail.com"
#profilepic: avatar-phpb.jpg
address: "Office SP 301.11, Department of Biology, Concordia University"
website: "pedrohbraga.github.io"
orcid: 0000-0002-1308-1562
googlescholar: ISSe8H0AAAAJ
languages: "**excellent written and oral proficiency**: English, French, Portuguese; **studied**: Japanese, German"
github: pedrohbraga
twitter: pedrohp_braga
attributes: "cooperative skills, proactive and resourceful team participation, adaptive management and organisational skills, public speaking and communication, cheerful $\\Summertree$"
#hobbies: "running, cycling, hiking, crafting and cooking"
interests: "As an **evolutionary ecologist** and a **biogeographer**, I am interested in using information on the **evolutionary history of species** and their **ecological attributes** to understand how **processes and mechanisms that generate biodiversity patterns**. In my research, I stress the **importance of phylogenetic and spatial scales and historical components of ecological and evolutionary drivers**. I practice and promote **open and reproducible science**. I am also dedicated towards the integration of evidence-based **active learning strategies** in my **teaching** and **scientific communication** abilities."
skillset: 
  - {cat: "Data Analysis", name: "I have a very strong foundation in R, where I concentrate most of my work. I have limited experience using Julia, SQL and MatLab."}
  - {cat: "Reproducibility", name: "I create reports and presentations using RMarkdown, markdown, Sweave, RShiny, and LaTeX. I collaborate and perform version control using Git."}
  - {cat: "Front-End and Back-End", name: "I am comfortable with using UNIX/Linux shell, and have limited experience with HTML, Go and CSS."}
  - {cat: "Spatial Data Operations", name: "I frequently perform spatial data operations using simple features and other R implementations (sf, sp, raster, rgeos, and others). I also have formal training and experience in using ArcGIS, QGIS, GDAL, GEOS and PROJ."}
  - {cat: "Statistical Foundation", name: "I have a skilled basis in statistical and quantitative methods. I frequently apply univariate and multivariate statistics (including, generalized linear (mixed) models, generalized additive models, Eigenanalysis-based models, autoregressive and filtering models), Bayesian inference (BAMM), and extend them to simulations, species distribution models, and spatial and phylogenetic comparative methods (under parallel computing, if necessary)."}
  - {cat: "Field and Laboratory", name: "I have four years of field and laboratory experience in bioacustics, zoology, sampling techniques, and identification of bats and frogs."}
edu:
  - {degree: Ph.D.,
     description_1: "Candidate in Biology",
     when: "2016 to *Current*",
     where: "Concordia University, Montréal, CA",
     description_2: "Thesis: *Spatial and phylogenetic scale-dependence in the evolutionary and ecological determinants of diversity patterns in bats*",
     description_3: "Supervisors: *Pedro **Peres-Neto*** & *Steven **Kembel***"}
  - {degree: Ph.D.,
     description_1: "Student in Biology",
     when: "2014 to 2016 - *Transfer*",
     where: "Université du Québec à Montréal, Montréal, CA",
     description_2: "Thesis: *Spatial and phylogenetic scale-dependence in the evolutionary and ecological determinants of diversity patterns in bats*",
     description_3: "Supervisors: *Pedro **Peres-Neto*** & *Steven **Kembel***"}
  - {degree: M.Sc.,
     when: "2012 to 2014",
     where: "Federal University of Goiás, Goiânia, BR",
     description_1: "in Ecology and Evolution",
     description_2: "Thesis: *Niche evolution and diversification patterns in Neotropical anurans*",
     description_3: "Supervisors: *Natan Medeiros **Maciel*** & *Paulo **De Marco***"}
  - {degree: B.Sc.,
     when: "2008 to 2012",
     where: "Federal University of Goiás, Goiânia, BR",
     description_1: "in Biological Sciences",
     description_2: "Honours Thesis: *Adaptive climatic niche evolution in bufonid frogs*",
     description_3: "Supervisors: *Natan Medeiros **Maciel*** & *Paulo **De Marco***"}
     
teaching:
  - {year: "Winter 2021", 
     where: "*Remote*", 
     what: "Generalized Linear Models in R",
     position: "Workshop Instructor"}  
  - {year: "Fall 2020", 
     where: "*Remote*", 
     what: "Introduction to Programming in R",
     position: "Workshop Instructor"}  
  - {year: "Winter-Fall 2019", 
     where: "Dawson College \n Concordia University", 
     what: "**S**upporting **A**ctive **L**earning and **T**echnological **I**nnovation in **S**tudies of **E**ducation (SALTISE)",
     position: "Pedagogical Formation"}
  - {year: "Winter 2019", 
     where: "Concordia University", 
     what: "Advanced Multivariate Analyses",
     position: "Workshop Instructor"}
  - {year: "Fall 2018", 
     where: "Concordia University", 
     what: "Biostatistics (BIOL322)",
     position: "Teaching Assistant"}
  - {year: "Fall 2018", 
     where: "Concordia University", 
     what: "QCBS R Workshop Series \ \nggplot & plyr \ \nProgramming in R ",
     position: "Workshop Instructor"}
  - {year: "Summer 2018", 
     where: "Concordia University", 
     what: "Fundamentals of Nutrition (BIOL203)",
     position: "Teaching Assistant"}
  - {year: "Winter 2018", 
     where: "Concordia University", 
     what: "Fundamentals of Nutrition (eBIOL203)",
     position: "Teaching Assistant (Remote Setting)"}
  - {year: "Winter 2018", 
     where: "Concordia University \n McGill University", 
     what: "QCBS R Workshop Series \ \nGeneralized Linear Mixed Models \ \nMultivariate Analyses",
     position: "Workshop Instructor"}
  - {year: "Fall 2017", 
     where: "Concordia University \n McGill University", 
     what: "QCBS R Workshop Series \ \nIntroduction to ggplot2 & dplyr \ \nLinear Models in R",
     position: "Workshop Instructor"}
  - {year: "Winter 2017", 
     where: "McGill University", 
     what: "QCBS R Workshop Series \ \nGeneralized Linear Mixed Models \ \nMultivariate Analyses",
     position: "Workshop Instructor"}
  - {year: "Fall 2016", 
     where: "Université du Québec à Montréal", 
     what: "Séminaire en écologie et analyses des données (BIO3500)",
     position: "Teaching Assistant"}
  - {year: "Fall 2016", 
     where: "McGill University", 
     what: "QCBS R Workshop Series \ \nIntroduction to R \ \nCharger et manipuler des données en R \ \nLoading and manipulating data in R \ \nIntroduction to ggplot \ \nLinear models \ \nProgramming in R",
     position: "Workshop Instructor"}
  - {year: "Winter 2016", 
     where: "McGill University", 
     what: "QCBS R Workshop Series \ \nLinear mixed models \ \nAdvanced multivariate analyses \ \nProgramming in R",
     position: "Workshop Instructor"}
  - {year: "Winter 2013", 
     where: "Federal University of Goiás", 
     what: "Biostatistics",
     position: "Teaching Assistant"}

mentoring:
  - {year: "2016-2017",
     student: "Wayne Toh",
     what: "Peer-mentoring under the Concordia Biology Graduate-Undergraduate Mentorship Program",
     where: "Concordia University"}
  - {year: "2013", 
     student: "Larissa Pereira Lemes",
     what: "Co-supervision with Dr. Natan Medeiros Maciel on her honour thesis: *Effectiveness and priority areas for anuran conservation in Brazil*",
     where: "Federal University of Goiás"}

professional:
  - {year: "2017-*Current*", 
     where: "Montréal, Canada", 
     what: "Québec Centre for Biodiversity Science",
     position: "Coordinator for the QCBS R Workshop Series"}
  - {year: "2018", 
     where: "Montréal, Canada", 
     what: "3rd Québec Centre for Biodiversity Science R Symposium",
     position: "Event planner and coordinator"}
  - {year: "2017", 
     where: "Montréal, Canada", 
     what: "2nd Québec Centre for Biodiversity Science R Symposium",
     position: "Event planner and coordinator"}
  - {year: "2017", 
     where: "Montréal, Canada", 
     what: "Québec Centre for Biodiversity Science Symposium",
     position: "Event committee member for the eco-responsible certification"}
  - {year: "2016", 
     where: "Montréal, Canada", 
     what: "Québec Centre for Biodiversity Science Symposium",
     position: "Event committee member for the eco-responsible certification"}          
  - {year: "2015", 
     where: "Mont-Saint-Hilaire, Canada", 
     what: "Organization of the QCBS Research Derby",
     position: "Event planner and organizer"}         
  - {year: "2013-2014", 
     where: "*Remote*", 
     what: "Biostatistical consulting on research projects varying from clinical study designs to ecological research",
     position: "Statistical Consultant"}
  - {year: "2011-2012", 
     where: "Montividiu and Paraúna, Brazil", 
     what: "Environmental Assessment for Cosan Limited S.A. Sugar Cane Industries",
     position: "Environmental Fieldwork Assessment (Chiroptera and Anura) and Statistical Consultant"}
  - {year: "2011-2012", 
     where: "Barro Alto and Niquelândia, Brazil", 
     what: "Biodiversity monitoring of the areas that are directly influenced by Anglo American Brazil’s activities as part of the agreement with the Federal University of Goiás",
     position: "Research Technician"}
  - {year: "2011-2012", 
     where: "Goiânia, Brazil",
     what: "XXII Conference for the Institute of Biological Sciences from the Federal University of Goiás",
     position: "Conference organizer"}
     

award:
  - {year: "2020", 
     name: "**Bursary**: Natural Sciences and Engineering Research Council (NSERC) Discovery Grant",
     value: "CAD 5,000"}
  - {year: "2020", 
     name: "**Bursary**: Natural Sciences and Engineering Research Council (NSERC) Discovery Grant",
     value: "CAD 5,000"}
  - {year: "2019", 
     name: "**Award**: Excellence Award from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 1,279"}
  - {year: "2014-2018",
     name: "**Scholarship**: Science without Borders Ph.D. Scholarship from the National Council of Research and Development (CNPq) (249289/2013-0)",
     value: "CAD 180,000"}
  - {year: "2018", 
     name: "**Award**: Learning and Development Award (LeaDA) from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 1,825"}
  - {year: "2018", 
     name: "**Award**: Excellence Award from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 1,140"}
  - {year: "2017", 
     name: "**Award**: Learning and Development Award (LeaDA) from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 250"}
  - {year: "2017", 
     name: "**Award**: Learning and Development Award (LeaDA) from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 963"}
  - {year: "2015", 
     name: "**Award**: Non-tuition fees funding for the Intensive Course in Biodiversity Science from the Québec Centre for Biodiversity Science (QCBS)", 
     value: "CAD 1380"}
  - {year: "2015", 
     name: "**Grant**: Deutscher Akademischer Austauschdienst (DAAD) travel grant for the 2015 iDiv Summer School on Biodiversity Synthesis", 
     value: "EUR 1,450"}
  - {year: "2012-2014", 
     name: "**Scholarship**: M.Sc. Scholarship from the Coordination for the Improvement of Higher Education Personnel (CAPES)", 
     value: "BRL 28,800"}
  - {year: "2011-2012", 
     name: "**Scholarship**: National Council of Research and Development (CNPq) Undergraduate Research Scholarship",
     value: "BRL 3,000"}
     
membership: 
  - {year: "2016-*Current*", name: "International Biogeography Society, Student Member"}
  - {year: "2015-2019", name: "Québec Centre for Biodiversity Science, Student Representative"}
  - {year: "2017-2017", name: "Ecology Society of America, Student Member"}
  - {year: "2011-2012", name: "Brazilian Herpetology Society, Student Member"}

reviewer:
  - {year: 2021, journal: "Marine Biology, Zoology"}
  - {year: 2019, journal: "Diversity and Distributions"}

bibliography: phpb-googlescholar.bib

csl: apa.csl

nocite: |
  @fournier2020spatialfrequency,
  @peixoto2018synthesis, 
  @peixoto2014global, 
  @batista2013dendropsophus,
  @maciel2013distribution
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library("googlesheets4")
library("tidyverse")
library("glue")
```


```{r presentations, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
# gs4_auth()
presentations <- read_sheet("https://docs.google.com/spreadsheets/d/1uBPoPzRA4aY4tSeYbMXjpqEYKE0aGUEzKEopnxYyd9k/edit?usp=sharing") %>%
   arrange(invited, 
          desc(when))

save(presentations, 
     file = "phpb-presentations.rda")
```

```{r load-presentations, message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}
load("phpb-presentations.rda")
```

# Contributed Presentations
\vspace{-0.05cm}

```{r, results = "asis", echo = FALSE}
contrib <- presentations %>%
  filter(invited == 0) %>%
  arrange(-when)

glue::glue_data(contrib, 
                "**>venue<** \\fn{>what<}",
                "\\begin{quote}>gsub('\\\\*', '', who)<, \\href{>link<}{>title<}. \\textit{>venue<}. (>when<). >where<.\\end{quote}",
                .open = ">", .close = "<")
```

# Outreach
\vspace{-0.05cm}

```{r, results = "asis", message = FALSE, warning = FALSE, echo = FALSE}
invited <- presentations %>%
  filter(invited == 1) %>%
  arrange(-when)

glue::glue_data(invited, 
                "**>venue<** \\fn{>what<}",
                "\\begin{quote}>gsub('\\\\*', '', who)<, \\href{>link<}{>title<}. \\textit{>venue<}. (>when<). >where<.\\end{quote}",
                .open = ">", 
                .close = "<")
```

# Peer-reviewed Publications
\vspace{-0.05cm}
